### ISSUE TITLE
`RSpec/DescribeClass`: Add "task" type to IgnoredMetadata (to exclude rake task specs from this cop)

### ISSUE THREAD

**Issue by harry-graham** [rubocop/rubocop-rspec#1218]
Add a `task` type to IgnoredMetadata for the **RSpec/DescribeClass** cop.

Rake tasks are not defined under a class, and so are always flagged by this rule unless the project has a custom exception to exclude this.

### Example rake task (from [RailsGuides](https://guides.rubyonrails.org/v4.2/command_line.html#rake))

```
namespace :db do
  desc "This task does nothing"
  task :nothing do
    # Seriously, nothing
  end
end
```

### Current cop default config ([here](https://github.com/rubocop/rubocop-rspec/blob/7cf850deaf1c7d85b41cef1802106e4ec31193bd/config/default.yml#L175))

The current defaults do not include a type that can be used for rake tasks.

```
RSpec/DescribeClass:
  Description: Check that the first argument to the top-level describe is a constant.
  Enabled: true
  Exclude:
    - "**/spec/features/**/*"
    - "**/spec/requests/**/*"
    - "**/spec/routing/**/*"
    - "**/spec/system/**/*"
    - "**/spec/views/**/*"
  IgnoredMetadata:
    type:
      - channel
      - controller
      - helper
      - job
      - mailer
      - model
      - request
      - routing
      - view
      - feature
      - system
      - mailbox
      - aruba
  VersionAdded: '1.0'
  VersionChanged: '2.5'
  StyleGuide: https://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/DescribeClass
```

### Versions tested
```
$ rubocop -V
1.20.0 (using Parser 3.0.2.0, rubocop-ast 1.12.0, running on ruby 2.6.5 -darwin20)
  - rubocop-performance 1.11.5
  - rubocop-rails 2.12.4
  - rubocop-rspec 2.5.0
```

### Background - what is rake?

Rake is used significantly in rails. RailsGuides has a large section on rake [here](https://guides.rubyonrails.org/v4.2/command_line.html#rake).

> _Rake is Ruby Make, a standalone Ruby utility that replaces the Unix utility 'make', and uses a 'Rakefile' and .rake files to build up a list of tasks. In Rails, Rake is used for common administration tasks, especially sophisticated ones that build off of each other._

Rake is a heavily used utility within rails, and so it makes sense to make this gem as compatible as possible with rake.
