### ISSUE TITLE
RSpec/ImplicitSubject does not use example methods defined by third-party gems

### ISSUE THREAD

**Issue by inkstak** [rubocop/rubocop-rspec#1290]
I use saharspecs and its `its_call` alias :

```
its_call(1) do
  is_expected
    .to  send_message(Foo, :method).once
    .and change { whatever }
end
```

I've add saharspec aliases to rubocop and  RSpec/ImplicitSubject is set to accept single statement

```
inherit_gem:
  saharspec: config/rubocop-rspec.yml

[...]

RSpec/ImplicitSubject:
  EnforcedStyle: single_statement_only
```

It report offenses on Implicit subject:

```
RSpec/ImplicitSubject: Don't use implicit subject. (https://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/ImplicitSubject)
    is_expected
    ^^^^^^^^^^^
```

I've got the same error when I set RSpec/ImplicitSubject to accept single line

```
its_call(1) { is_expected.to send_message(Foo, :method).once }
```
```
RSpec/ImplicitSubject:
  EnforcedStyle: single_line_only
```
```
RSpec/ImplicitSubject: Don't use implicit subject. (https://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/ImplicitSubject)
  its_call(1) { is_expected.to send_message(Foo, :method).once }
                ^^^^^^^^^^^
```
