### ISSUE TITLE
[Feature request] Allow specifying `it` aliases for RSpec/EmptyExampleGroup

### ISSUE THREAD

**Issue by Epigene** [rubocop/rubocop-rspec#1346]
**Problem:**
RSpec allows aliasing the `it` method to other words, `they` is a popular choice for plural "things under test", see [this SO thread](https://stackoverflow.com/a/12320874/3319298).  
Then using these aliases will produce false positives for `RSpec/EmptyExampleGroup` cop, for example

```rb
describe "cookies" do # < offensive to RSpec/EmptyExampleGroup because no `it` appears in the block
  they "are tasty" do
    # some asserts
  end
end
```

**Solution:**
Expose some "ItAliases" configuration option to also take the aliases into account.

```yaml
RSpec/EmptyExampleGroup:
  Enabled: true
  ItAliases:
    - they   
```
