### ISSUE TITLE
RSpec/ContextWording: incorrect sample about AllowedPatterns

### ISSUE THREAD

**Issue by takaki** [rubocop/rubocop-rspec#1395]
It is written in source code comment 
```yaml
RSpec/ContextWording:
  AllowedPatterns:
    - /とき$/
```
But it does not working.
It should be instead of 
```
    - とき$
```
