### ISSUE TITLE
Fix output of "RSpec/Capybara" namespace not being enabled

### ISSUE THREAD

**Issue by bkuhlmann** [rubocop/rubocop-rspec#1561]
## Overview

Hello. :wave: With the release of RuboCop RSpec 2.18.0, the following output is constantly displayed in the console:

``` 
config/rspec.yml: RSpec/Capybara/MatchStyle has the wrong namespace - should be Capybara
config/rspec.yml: RSpec/Capybara/NegationMatcher has the wrong namespace - should be Capybara
config/rspec.yml: RSpec/Capybara/SpecificActions has the wrong namespace - should be Capybara
config/rspec.yml: RSpec/Capybara/SpecificFinders has the wrong namespace - should be Capybara
config/rspec.yml: RSpec/Capybara/SpecificMatcher has the wrong namespace - should be Capybara
The following cops were added to RuboCop, but are not configured. Please set Enabled to either `true` or `false` in your `.rubocop.yml` file.

Please also note that you can opt-in to new cops by default by adding this to your config:
  AllCops:
    NewCops: enable

RSpec/Capybara/MatchStyle: # new in 2.17
  Enabled: true
RSpec/Capybara/NegationMatcher: # new in 2.14
  Enabled: true
RSpec/Capybara/SpecificActions: # new in 2.14
  Enabled: true
RSpec/Capybara/SpecificFinders: # new in 2.13
  Enabled: true
RSpec/Capybara/SpecificMatcher: # new in 2.12
  Enabled: true
For more information: https://docs.rubocop.org/rubocop/versioning.html
```

Prior to upgrading to 2.18.0 (i.e. using 2.17.0) this output didn't exist. It appears the rename of cops isn't working as intended.

## Steps to Recreate

If you rename the namespace so that `RSpec` is dropped and only `Capybara` is used. Like this:

``` yaml
Capybara/MatchStyle:
  Enabled: true
Capybara/NegationMatcher:
  Enabled: true
Capybara/SpecificActions:
  Enabled: true
Capybara/SpecificFinders:
  Enabled: true
Capybara/SpecificMatcher:
  Enabled: true
```

...you'll then get the following output but only slightly cleaned up:

``` 
The following cops were added to RuboCop, but are not configured. Please set Enabled to either `true` or `false` in your `.rubocop.yml` file.

Please also note that you can opt-in to new cops by default by adding this to your config:
  AllCops:
    NewCops: enable

RSpec/Capybara/MatchStyle: # new in 2.17
  Enabled: true
RSpec/Capybara/NegationMatcher: # new in 2.14
  Enabled: true
RSpec/Capybara/SpecificActions: # new in 2.14
  Enabled: true
RSpec/Capybara/SpecificFinders: # new in 2.13
  Enabled: true
RSpec/Capybara/SpecificMatcher: # new in 2.12
  Enabled: true
For more information: https://docs.rubocop.org/rubocop/versioning.html
Inspecting 12 files
```

## Environment

``` 
1.43.0 (using Parser 3.2.0.0, rubocop-ast 1.24.1, running on ruby 3.2.0) [arm64-darwin22.2.0]
  - rubocop-performance 1.15.2
  - rubocop-rake 0.6.0
  - rubocop-rspec 2.18.0
  - rubocop-thread_safety 0.4.4
```

**Comment by pirj** [comment]
So if you downgrade to 2.17, what the output would be? From your report, I imply that the following section was not printed?
```
The following cops were added to RuboCop, but are not configured.
```
Is that correct?
Did you disable/enable those `RSpec/Capybara` cops somewhere in your `.rubocop.yml` configuration?

**Comment by ydah** [comment]
Perhaps, but this seems to happen when Enabling/Disabling Pending Cops in Bulk is not set as follows.
https://docs.rubocop.org/rubocop/versioning.html#enablingdisabling-pending-cops-in-bulk

We have confirmed that this occurs when you have a `.rubocop.yml` like the following:
```yaml
require:
  - rubocop-rspec

AllCops:
  SuggestExtensions: false

Capybara/MatchStyle: # new in 2.17
  Enabled: true
Capybara/NegationMatcher: # new in 2.14
  Enabled: true
Capybara/SpecificActions: # new in 2.14
  Enabled: true
Capybara/SpecificFinders: # new in 2.13
  Enabled: true
Capybara/SpecificMatcher: # new in 2.12
  Enabled: true
```
If we run RuboCop in this state, we will get the following warning:
```
The following cops were added to RuboCop, but are not configured. Please set Enabled to either `true` or `false` in your `.rubocop.yml` file.

Please also note that you can opt-in to new cops by default by adding this to your config:
  AllCops:
    NewCops: enable

Gemspec/DeprecatedAttributeAssignment: # new in 1.30
  Enabled: true
(snip)
RSpec/Capybara/MatchStyle: # new in 2.17
  Enabled: true
RSpec/Capybara/NegationMatcher: # new in 2.14
  Enabled: true
RSpec/Capybara/SpecificActions: # new in 2.14
  Enabled: true
RSpec/Capybara/SpecificFinders: # new in 2.13
  Enabled: true
RSpec/Capybara/SpecificMatcher: # new in 2.12
  Enabled: true
:
For more information: https://docs.rubocop.org/rubocop/versioning.html
```

**Comment by ydah** [comment]
This is a warning that is output when the enable/disable setting is not set, and it seems that the following settings are necessary to eliminate it.

```yaml
AllCops:
  NewCops: disable

Capybara/MatchStyle: # new in 2.17
  Enabled: true
Capybara/NegationMatcher: # new in 2.14
  Enabled: true
Capybara/SpecificActions: # new in 2.14
  Enabled: true
Capybara/SpecificFinders: # new in 2.13
  Enabled: true
Capybara/SpecificMatcher: # new in 2.12
  Enabled: true
```

or

```yaml
Capybara/MatchStyle: # new in 2.17
  Enabled: true
Capybara/NegationMatcher: # new in 2.14
  Enabled: true
Capybara/SpecificActions: # new in 2.14
  Enabled: true
Capybara/SpecificFinders: # new in 2.13
  Enabled: true
Capybara/SpecificMatcher: # new in 2.12
  Enabled: true
RSpec/Capybara/MatchStyle:
  Enabled: false
RSpec/Capybara/NegationMatcher:
  Enabled: false
RSpec/Capybara/SpecificActions:
  Enabled: false
RSpec/Capybara/SpecificFinders:
  Enabled: false
RSpec/Capybara/SpecificMatcher:
  Enabled: false
```

**Comment by bkuhlmann** [comment]
> **Phil**: So if you downgrade to 2.17, what the output would be?

Correct, if I downgrade, the issue goes away. Here's a screenshot:

![2023-01-17_06-35-24-iTerm2](https://user-images.githubusercontent.com/50245/212913010-19d8753c-b377-42c1-971e-cfbd382da9bd.png)

> **Yudai**: This is a warning that is output when the enable/disable setting is not set

I can confirm as well. If I ensure `NewCops: disable` is set then this works. Here's a screenshot:

![2023-01-17_06-45-49-iTerm2](https://user-images.githubusercontent.com/50245/212915155-de3f03cb-bb47-42cf-993a-9fb10af74c12.png)

I like not having `NewCops` enabled or disabled because it's a handy way to detect changes in new versions of RuboCop and update accordingly. Should I log this issue against RuboCop Core instead?

**Comment by ydah** [comment]
These warnings will appear because RuboCop RSpec 2.17 has extracted RuboCop Capybara's cops.
So there is a move of departments from `RSpec/Capybara/FooCop` to `Capybara/FooCop`.

However, both `RSpec/Capybara/FooCop` and `Capybara/FooCop` exist as pending for compatibility.
So, as shown below, by disabling the `RSpec/Capybara` department and enabling the `Capybara` department, I don't think the corresponding warning will appear without the `NewCops` enable/disable setting, right?

```
require:
  - rubocop-capybara
  - rubocop-rspec

(snip)

Capybara/MatchStyle:
  Enabled: true
Capybara/NegationMatcher:
  Enabled: true
Capybara/SpecificActions:
  Enabled: true
Capybara/SpecificFinders:
  Enabled: true
Capybara/SpecificMatcher:
  Enabled: true
RSpec/Capybara:
  Enabled: false
RSpec/Capybara/FeatureMethods:
  Enabled: true
```
