### ISSUE TITLE
RSpec/IndexedLet should allow identifiers defined in Naming/VariableNumber: AllowedIdentifiers

### ISSUE THREAD

**Issue by pjg** [rubocop/rubocop-rspec#1622]
With the following configuration:

```yaml
Naming/VariableNumber:
  AllowedIdentifiers:
    - "address_line_1"
    - "address_line_2"
```

rubocop-rspec will still report `RSpec/IndexedLet` offence with this code:

```ruby
let!(:address_line_1) { 'line1' }
let!(:address_line_2) { 'line2' }
```

It would be better if the `RSpec/IndexedLet` cop would read the configuration for `AllowedIdentifiers` in the `Naming/VariableNumber` cop and ignored those.
