### ISSUE TITLE
Fix for #1663 causes `RSpec/Pending` to give false positive with rswag

### ISSUE THREAD

**Issue by Tabby** [rubocop/rubocop-rspec#1678]
When using [rswag](https://github.com/rswag/rswag), tests are generally all of the form:

```ruby
response '201', 'foo created' do
  let(:foo) { { content: 'bar' } }

  run_test!
end
```

As of rubocop-rspec v2.23.0, that call to `run_test!` is being flagged as a violation of `RSpec/Pending`. I believe it's because it's being treated as an example without a body, even though it is actually a method call which runs a complete test case as the only relevant change since v2.22.0 is #1664.

I don't know if this is an issue with a regex that determines what constitutes an example declaration, or if it's something that could be solved by allowing configurable patterns to be ignored by this cop, but as it is I will need to pin rubocop-rspec to `<2.23.0` because otherwise we get hundreds of erroneous violations of this rule

**Comment by ydah** [comment]
Would it be good to have `AllowedIdentifiers` or `AllowedPatterns` settings?

**Comment by Tabby** [comment]
I think that would probably be the best option if it's possible, yes :)

I think allowing for edge cases is a more appropriate solution than just trying to cover all possible edge cases in the cop implementation, and it's hopefully not too much work to add it in

**Comment by pirj** [comment]
> that call to run_test! is being flagged as a violation of RSpec/Pending

Can you please help me understand, why? How?
It shouldn’t even be detected as example group/example?

**Comment by ydah** [comment]
Maybe, but I think it is set up as follows:
```yaml
RSpec:
  Language:
    Examples:
      Regular:
        - run_test!

RSpec/Pending:
  Enabled: true
```

However, with this setting, perhaps the configuration is wrong and should be changed as follows.

```yaml
RSpec:
  Language:
    Expectations:
      - run_test!

RSpec/Pending:
  Enabled: true
```

**Comment by ydah** [comment]
@Tabby Can you provide a .rubocop.yml to reproduce if possible?

**Comment by Tabby** [comment]
Apologies, I should have done that to begin with >_>

In doing so, I found that the `.rubocop.yml` in the repo I'd seen this was configured with the following to try and handle the additional DSL methods added by rswag:

```
RSpec:
  Language:
    ExampleGroups:
      Regular:
        - path
        - post
        - put
        - get
        - delete
        - response
    Examples:
      Regular:
        - run_test!
```

This is not correct, as you pointed out. I've now fixed it by changing it in a similar manner to your suggestion.

This no longer raises any violations with rubocop-rspec v2.23.0 so this issue was just a misconfiguration and not a bug. Thanks for looking into it and sorry for the wasted time
