### ISSUE TITLE
Improvement: Configurable option for `Rails/TransactionExitStatement`

### ISSUE THREAD

**Issue by marocchino** [rubocop/rubocop-rspec#1700]
Hi. 

We differentiate transactions by using methods with different names depending on the target DB. 
So I would like to be able to leave the transaction on_lock as the default and add another method name to use it.

like..

```yaml
Rails/TransactionExitStatement:
  TransactionMethods:
    - transaction
    - on_lock
    - some_custom
```
