### ISSUE TITLE
Error: "Ambiguous cop name `RSpec/Rails/HttpStatus`"

### ISSUE THREAD

**Issue by Drowze** [rubocop/rubocop-rspec#1858]
Started to get the error on v2.28.0 (I believe due to this change: https://github.com/rubocop/rubocop-rspec/pull/1830). 

## Reproducing it:

Gemfile:
```ruby
source "https://rubygems.org"
gem "rubocop-rspec"
gem "rubocop-rails"
```

.rubocop.yml:
```yaml
require:
  - rubocop-rails
  - rubocop-rspec

RSpec/Rails/HttpStatus:
  Enabled: true
```

```
$ bundle exec rubocop
Error: Ambiguous cop name `RSpec/Rails/HttpStatus` used in /Users/Drowze/rubocop-issue/.rubocop.yml needs department qualifier. Did you mean Rails/HttpStatus or RSpecRails/HttpStatus?
```
