### ISSUE TITLE
RSpec/Dialect causes a false negative when using below setting mentioned in the documentation

### ISSUE THREAD

**Issue by sanfrecce-osaka** [rubocop/rubocop-rspec#1951]
RSpec/Dialect causes a false negative when using below setting mentioned in the documentation.

```yaml
RSpec/Dialect:
  PreferredMethods:
    background: :before
    scenario:   :it
    xscenario:  :xit
    given:      :let
    given!:     :let!
    feature:    :describe
```

cf. https://docs.rubocop.org/rubocop-rspec/cops_rspec.html#rspecdialect

## Expected behavior

The following code should not be passed:

```ruby
background do # 👮‍♂️ C: [Correctable] RSpec/Dialect: Prefer before over background.
  # some setup codes
end
```

## Actual behavior

The following code is passed:

```ruby
background do
  # some setup codes
end
```

In contrast, the following codes doesn't pass.

```ruby
RSpec.feature do
  # some codes
end
```

```ruby
scenario do
  # some codes
end
```

```ruby
xscenario do
  # some codes
end
```

I look like `rspec_method?` returns nil when `node.method_name` is `background`.

https://github.com/rubocop/rubocop-rspec/blob/e02576f1a8c39d9dc5b3ca37fea4596f7e75f493/lib/rubocop/cop/rspec/dialect.rb#L67-L80

## RuboCop version

```
$ bundle exec rubocop -V
1.65.1 (using Parser 3.3.4.2, rubocop-ast 1.32.0, running on ruby 3.2.3) +server [arm64-darwin21]
  - rubocop-capybara 2.21.0
  - rubocop-factory_bot 2.26.1
  - rubocop-performance 1.21.1
  - rubocop-rails 2.25.1
  - rubocop-rspec 3.0.4
  - rubocop-rspec_rails 2.30.0
```
