### ISSUE TITLE
Allow ignoring by multiple metadata entries in RSpec/SpecFilePathFormat

### ISSUE THREAD

**Issue by pirj** [rubocop/rubocop-rspec#2084]
## Is your feature request related to a problem? Please describe.

Presently, `IgnoreMetadata` only allows a single value, thus not allowing to ignore specs with e.g. `type: :model` and `type: :routing`.

## Describe the solution you'd like

Allow `IgnoreMetadata` to have multiple values.

```yaml
IgnoreMetadata:
  - prepare # ignore by presence of a key
  - type: model # ignore one value
  - type: routing # and another, too
  - skip: [database] # ignore when the value is an array of specific values
```

## Describe alternatives you've considered

-

## Additional context

See #2070 and #2076 for draft PRs. This issue, however, suggests a different approach.

⚠ The cop should be able to handle both the old and the new config format for that option.
