### ISSUE TITLE
Feature request: RSpec/ContextWording supports Japanese

### ISSUE THREAD

**Issue by pocke** [rubocop/rubocop-rspec#745]
# Problem

RSpec/ContextWording does not work well to check Japanese.
It has two problems.

First, usually we use a suffix to specify "when". For example, `when a user exists` is translated to `ユーザーが存在する時`. `時` means `when`.
But the cop only supports prefix, so we cannot configure it for Japanese.

Second, Japanese does not separate words with space.  For example, `ユーザー が 存在する 時` is not appropriate as Japanese. 
But the cop split the sentence with space.
https://github.com/rubocop-hq/rubocop-rspec/blob/0442757fb4af570994b37b3e0ca35baeec635eb0/lib/rubocop/cop/rspec/context_wording.rb#L45
So If the cop supports suffix, it does not enough. 

# Solution Ideas

I have two ides.

First, adding `Suffixes` and `Split` options to the cop.
For example:

```yaml
RSpec/ContextWording:
  Suffixes:
    - '時'
  Split: false # default: true
```

The cop splits context sentence only if `Split` option is enabled. If it is disabled, the cop just checks with `start_with` or `end_wtih` method.

Second, adding `Patterns` option to the cop.
For example

```yaml
RSpec/ContextWording:
  Patterns:
    - "^when"
    - "^if"
    # Suffix pattern for japanese
    - "時$"
```

---

I like the first idea. The second idea is more powerful, but I think we do not need regexp in most cases.

---

The original idea is issued in rubocop-hq/rubocop-jp by @kyohah. https://github.com/rubocop-hq/rubocop-jp/issues/49
Thank you!
